development:
  twitter:
    consumer_key: ""
    consumer_secret: ""
    access_token: ""
    access_token_secret: ""

test:
  twitter:
    consumer_key: ""
    consumer_secret: ""
    access_token: ""
    access_token_secret: ""
