development:
  twitter:
    consumer_key: ""
    consumer_secret: ""
    access_token: ""
    access_token_secret: ""
  news_api:
    api_key: ""

test:
  twitter:
    consumer_key: ""
    consumer_secret: ""
    access_token: ""
    access_token_secret: ""
  news_api:
    api_key: ""